# Generated by Django 5.0.1 on 2024-02-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description of product')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, max_length=500, verbose_name='price')),
                ('img', models.ImageField(blank=True, null=True, upload_to='None')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop.category', verbose_name='category')),
            ],
        ),
    ]
